apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero-sample
  namespace: openshift-adp
spec:
  backupImages: true
  backupLocations:
    - velero:
        config:
          profile: default
          region: ap-south-1
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: openshift.sebastian-colomar.es
          prefix: velero
        provider: aws
  configuration:
    restic:
      enable: true
    velero:
      defaultPlugins:
        - openshift
        - aws
  snapshotLocations:
    - velero:
        config:
          profile: default
          region: ap-south-1
        provider: aws
